### ISSUE TITLE
Publish versioned JSON tracking protection lists to S3

### ISSUE THREAD

**Issue by say-yawn** [mozilla-services/shavar-list-creation#174]
# About this Issue
Publish the JSON tracking protection lists (and the versioned lists) to S3 so that iOS can download the latest tracking protection lists in JSON

# Acceptance Criteria
- [ ] JSON tracking protection lists are published to S3
- [ ] Versioned tracking protection lists in JSON are published to S3
- [ ] (Nice-To-Have) Only the latest changes on the latest release are being generated in JSON file and published to S3

**Comment by HarshitSohaney** [comment]
Since we are pushing towards moving lists to remote settings, iOS can directly use RS for the latest tracking protection lists.

This can be closed!

**Comment by artines1** [comment]
We can close this issue once iOS uses RS to fetch the list.
